#!/bin/sh

while read file
do
	case "$1" in 
		"w") setbg $file ;;
		"c") cat $file | xclip -sel c -t image/png ;;
		"r") convert $file -rotate 90 /tmp/out.jpg ;;
		"m") curl -F"file=@$file" 0x0.st | xclip -sel c
	esac
done
