#!/bin/sh

#  "", "", "", "", "", "", "", "", ""

bspc monitor -d 一 二 三 四 五 六 七 八 九 
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"#44475a"
bspc config active_border_color	"#bd93f9"
bspc config focused_border_color      "#ff79c6"
bspc config presel_feedback_color     "#6272a4"
bspc config urgent_border_color       "#dd2727"

bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

bspc config external_rules_command "$XDG_CONFIG_HOME/bspwm/external_rules"

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Pcmanfm state=floating
bspc rule -a supertuxkart state=tiled
bspc rule -a Pavucontrol state=floating
bspc rule -a St desktop=^2
bspc rule -a kitty desktop=^2
bspc rule -a firefox desktop=^1
bspc rule -a Virt-manager state=floating
bspc rule -a Galculator state=floating
bspc rule -a Screenkey manage=off
