#!/bin/bash

# I used apt-fast here but I assume that you dont have that enabled, so you have to use apt-get.

# Dependencies- awk dmenu

# This script can be easily modified to be usable on arch :)

action=$(echo -e "Install Program\nRemove Program\nRemove Waste\nUpdate System" | dmenu -p "Software Manager: " -i)

case $action in
	"Install Program")
		package=$(apt-fast list | awk -F'/' 'NR>1{print $1}' | sort -d | dmenu -i -l 20)

		sudo apt-fast install $package -y
		notify-send "$package is installed"
		;;
	 "Remove Program")
		 package=$(apt-fast list --installed | awk -F'/' 'NR>1{print$1}'  | sort -d | dmenu -i -l 20)

		 sudo apt-fast remove $package -y
		 notify-send "$package is removed"
		 ;;
	 "Remove Waste")
		 sudo apt-fast autoremove -y
		 notify-send 'Orphan packages removed'
		 ;;
	 "Update System")
		 sudo apt-fast update -y
		 notify-send 'System update completed'
		 ;;
	*)
	notify-send 'no option selected'
	;;
esac
